from dotenv import load_dotenv
from prompt_system import *
from model_selection import model_str
from time import sleep
from utils import *

load_dotenv()

_, parser, client = initial_parameters()
parameters = {
    "temperature": 1,
    "max_tokens": 250,
    "top_p": 1,
    "frequency_penalty": 0,
    "presence_penalty": 0
}

personality = prompt_system_persona_selection

def select_persona(user_message):
    """
    Selects a persona based on the user's message and generates a response using a chat completion model.

    Args:
        user_message (str): The message input from the user.

    Returns:
        str: The text response generated by the chat completion model.

    Raises:
        Exception: If there is an error in generating the response.

    """
    prompt_system = prompt_system_persona_selection
    selected_model = model_str(prompt_system, user_message)
    response = client.chat.completions.create(
        messages=[
            {
                "role": "system",
                "content": prompt_system
            },
            {
                "role": "user",
                "content" : user_message
            }
        ],
        **parameters,
        model = selected_model,
    )
    text_response = parser.invoke(response.choices[0].message.content.lower())
    return text_response